name: Create duck image
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - name: Sanitize Version
        run: |
          SET VERSION=${GITHUB_REF#refs/tags/release-}
          SET VERSION=${VERSION//-/.}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Disable Testcontainers for Windows and MacOS
        run: echo "args=-P=no-testcontainers" >> "$GITHUB_ENV"
        shell: bash
        if: runner.os == 'windows' || runner.os == 'macos' || runner.os == 'macos'
      - run: msiexec /i setup\wix\Bonjour64.msi /Quiet /Passive /NoRestart
        if: runner.os == 'windows'
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'windows'
      - uses: microsoft/setup-msbuild@v2
        if: runner.os == 'windows'
        with:
          msbuild-architecture: x64
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn verify -DskipTests -DskipSign -Pinstaller -Drevision=0 --projects cli/windows --also-make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-raw
          path: windows/target/*.exe
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-installer
          path: windows/target/release/*.exe
